//! Bundles the UI assets that live beside the maud templates.
//!
//! Styles and scripts sit next to the template that uses them. This script
//! minifies them (lightningcss for styles, oxc for scripts) into a few
//! bundles in Cargo's `OUT_DIR`, next to copies of the files in
//! `src/templates/static`, and generates `assets.rs`. That file embeds each
//! asset, plain and gzipped, with `include_bytes!` under a URL containing a
//! hash of its content. Nothing is written to the source tree.

use std::{
    env,
    error::Error,
    fmt::Write as _,
    fs,
    io::{self, Write as _},
    path::{Path, PathBuf},
};

use flate2::{Compression, write::GzEncoder};
use lightningcss::stylesheet::{MinifyOptions, ParserOptions, PrinterOptions, StyleSheet};
use oxc::{
    allocator::Allocator,
    codegen::{Codegen, CodegenOptions},
    minifier::{Minifier, MinifierOptions},
    parser::Parser,
    span::SourceType,
};
use sha2::{Digest, Sha256};

/// The script that runs in `<head>`, before the page paints.
const HEAD_SCRIPT: &str = "layouts/head.js";
/// Scripts that only the raw data page loads.
const RAW_DATA_DIR: &str = "pages/raw_data";

struct Asset {
    /// Rust constant naming the asset in `assets.rs`.
    constant: &'static str,
    /// File stem of the public URL, before the hash.
    stem: &'static str,
    extension: &'static str,
    content_type: &'static str,
    bytes: Vec<u8>,
}

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=build.rs");
    let manifest = env::var_os("CARGO_MANIFEST_DIR").ok_or("CARGO_MANIFEST_DIR is missing")?;
    let output = env::var_os("OUT_DIR").ok_or("OUT_DIR is missing")?;
    let templates = Path::new(&manifest).join("src/templates");
    let static_dir = templates.join("static");
    let output = Path::new(&output);

    let mut files = Vec::new();
    collect(&templates, &mut files)?;
    files.sort();
    for file in &files {
        println!("cargo::rerun-if-changed={}", file.display());
    }

    let head = templates.join(HEAD_SCRIPT);
    let raw_data = templates.join(RAW_DATA_DIR);
    let scripts = |wanted: &dyn Fn(&Path) -> bool| -> Vec<PathBuf> {
        files
            .iter()
            .filter(|file| has_extension(file, "js") && !file.starts_with(&static_dir))
            .filter(|file| wanted(file))
            .cloned()
            .collect()
    };
    let head_scripts = scripts(&|file| file == head);
    if head_scripts.is_empty() {
        return Err(format!("{} is missing", head.display()).into());
    }

    let assets = [
        Asset {
            constant: "SITE_CSS",
            stem: "site",
            extension: "css",
            content_type: "text/css; charset=utf-8",
            bytes: stylesheet(&templates.join("styles.css"), &static_dir, &files)?,
        },
        Asset {
            constant: "HEAD_JS",
            stem: "head",
            extension: "js",
            content_type: "text/javascript; charset=utf-8",
            bytes: minify_scripts(&head_scripts)?,
        },
        Asset {
            constant: "SITE_JS",
            stem: "site",
            extension: "js",
            content_type: "text/javascript; charset=utf-8",
            bytes: minify_scripts(&scripts(&|file| {
                file != head && !file.starts_with(&raw_data)
            }))?,
        },
        Asset {
            constant: "RAW_DATA_JS",
            stem: "raw-data",
            extension: "js",
            content_type: "text/javascript; charset=utf-8",
            bytes: minify_scripts(&scripts(&|file| file.starts_with(&raw_data)))?,
        },
        // Vendored as published: htmx.org 1.9.10, dist/htmx.min.js.
        Asset {
            constant: "HTMX_JS",
            stem: "htmx",
            extension: "js",
            content_type: "text/javascript; charset=utf-8",
            bytes: fs::read(static_dir.join("htmx-1.9.10.min.js"))?,
        },
        Asset {
            constant: "USA_MAP_SVG",
            stem: "usa-map",
            extension: "svg",
            content_type: "image/svg+xml",
            bytes: fs::read(static_dir.join("usa-map.svg"))?,
        },
    ];

    let mut generated =
        String::from("// Generated by build.rs; edit the files under src/templates instead.\n");
    for asset in &assets {
        let file = format!("{}.{}", asset.stem, asset.extension);
        fs::write(output.join(&file), &asset.bytes)?;
        fs::write(output.join(format!("{file}.gz")), gzip(&asset.bytes)?)?;
        let digest = hex::encode(Sha256::digest(&asset.bytes));
        let url = format!(
            "/assets/{}.{}.{}",
            asset.stem,
            &digest[..16],
            asset.extension
        );
        writeln!(
            generated,
            "pub const {constant}: Asset = Asset {{ url: {url:?}, content_type: {content_type:?}, \
             bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}\")), \
             gzip: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}.gz\")) }};",
            constant = asset.constant,
            content_type = asset.content_type,
        )?;
    }
    let constants: Vec<_> = assets.iter().map(|asset| asset.constant).collect();
    writeln!(
        generated,
        "pub const ALL: &[Asset] = &[{}];",
        constants.join(", ")
    )?;
    fs::write(output.join("assets.rs"), generated)?;
    Ok(())
}

/// Every file below `directory`. Directories are watched too, so an added
/// or removed file triggers a rebuild.
fn collect(directory: &Path, files: &mut Vec<PathBuf>) -> io::Result<()> {
    println!("cargo::rerun-if-changed={}", directory.display());
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            collect(&path, files)?;
        } else {
            files.push(path);
        }
    }
    Ok(())
}

fn has_extension(path: &Path, extension: &str) -> bool {
    path.extension().is_some_and(|found| found == extension)
}

/// Minifies each script on its own and joins them. A script the parser
/// rejects fails the build.
fn minify_scripts(files: &[PathBuf]) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut bundle = String::new();
    for file in files {
        let code = minify_js(&fs::read_to_string(file)?)
            .map_err(|error| format!("{}: {error}", file.display()))?;
        bundle.push_str(&code);
        // Semicolons keep one script's last statement apart from the next.
        bundle.push_str(";\n");
    }
    Ok(bundle.into_bytes())
}

/// Every oxc call is here, because oxc's 0.x API changes between releases.
/// The source is parsed as a classic script, so its top-level names stay
/// global and are not renamed.
fn minify_js(source: &str) -> Result<String, String> {
    let allocator = Allocator::default();
    let parsed = Parser::new(&allocator, source, SourceType::script()).parse();
    if let Some(error) = parsed.diagnostics.errors().next() {
        return Err(error.to_string());
    }
    let mut program = parsed.program;
    let minified = Minifier::new(MinifierOptions::default()).minify(&allocator, &mut program);
    Ok(Codegen::new()
        .with_options(CodegenOptions::minify())
        .with_scoping(minified.scoping)
        .build(&program)
        .code)
}

/// Base styles first, then every component's styles, minified as one sheet.
fn stylesheet(
    base: &Path,
    static_dir: &Path,
    files: &[PathBuf],
) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut css = fs::read_to_string(base)?;
    for file in files {
        if has_extension(file, "css") && file != base && !file.starts_with(static_dir) {
            css.push('\n');
            css.push_str(&fs::read_to_string(file)?);
        }
    }
    let mut sheet = StyleSheet::parse(
        &css,
        ParserOptions {
            filename: "src/templates (combined CSS)".into(),
            ..ParserOptions::default()
        },
    )
    .map_err(|error| io::Error::other(format!("parse CSS: {error}")))?;
    sheet
        .minify(MinifyOptions::default())
        .map_err(|error| io::Error::other(format!("minify CSS: {error}")))?;
    let printed = sheet
        .to_css(PrinterOptions {
            minify: true,
            ..PrinterOptions::default()
        })
        .map_err(|error| io::Error::other(format!("print CSS: {error}")))?;
    Ok(printed.code.into_bytes())
}

fn gzip(bytes: &[u8]) -> io::Result<Vec<u8>> {
    let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
    encoder.write_all(bytes)?;
    encoder.finish()
}
