//! Bundles the UI assets that live beside the maud templates.
//!
//! Every `.css` and `.js` file under `src/templates` is concatenated and
//! minified into Cargo's `OUT_DIR`, along with the files in
//! `src/templates/static`. The generated `assets.rs` gives each file a
//! content-hashed URL and embeds its bytes, so the binary serves its own UI
//! and nothing is written to the source tree.

use std::{
    env,
    error::Error,
    fs, io,
    path::{Path, PathBuf},
};

use lightningcss::stylesheet::{MinifyOptions, ParserOptions, PrinterOptions, StyleSheet};
use oxc::{
    allocator::Allocator,
    codegen::{Codegen, CodegenOptions},
    minifier::{Minifier, MinifierOptions},
    parser::Parser,
    span::SourceType,
};
use sha2::{Digest, Sha256};
use walkdir::WalkDir;

fn main() -> Result<(), Box<dyn Error>> {
    let manifest = env::var_os("CARGO_MANIFEST_DIR").ok_or("CARGO_MANIFEST_DIR is missing")?;
    let output = env::var_os("OUT_DIR").ok_or("OUT_DIR is missing")?;
    let templates = Path::new(&manifest).join("src/templates");
    let static_dir = templates.join("static");
    let output = Path::new(&output);

    println!("cargo::rerun-if-changed=build.rs");

    let mut css_files = Vec::new();
    let mut js_files = Vec::new();
    let mut static_files = Vec::new();
    for entry in WalkDir::new(&templates).sort_by_file_name() {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type().is_dir() {
            // Cargo notices added files only in directories it watches.
            println!("cargo::rerun-if-changed={}", path.display());
            continue;
        }
        if path.starts_with(&static_dir) {
            static_files.push(path.to_path_buf());
        } else {
            match path.extension().and_then(|extension| extension.to_str()) {
                Some("css") => css_files.push(path.to_path_buf()),
                Some("js") => js_files.push(path.to_path_buf()),
                _ => continue,
            }
        }
        println!("cargo::rerun-if-changed={}", path.display());
    }
    // Base styles come first so component styles can refine them.
    let base_styles = templates.join("styles.css");
    css_files.sort_by_key(|path| (path != &base_styles, path.clone()));

    let css = minify_css(&concatenate(&css_files, "\n")?)?;
    // Newlines end trailing line comments; semicolons separate the scripts.
    let js = minify_javascript(&concatenate(&js_files, "\n;\n")?)?;

    let mut generated =
        String::from("// Generated by build.rs; edit the files in src/templates instead.\n");
    generated.push_str(&asset(output, "CSS", "site.css", css.as_bytes())?);
    generated.push_str(&asset(output, "JS", "site.js", &js)?);
    for path in &static_files {
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| format!("{} has no UTF-8 file name", path.display()))?;
        let constant = name
            .rsplit_once('.')
            .map_or(name, |(stem, _)| stem)
            .replace(|character: char| !character.is_ascii_alphanumeric(), "_")
            .to_ascii_uppercase();
        generated.push_str(&asset(output, &constant, name, &fs::read(path)?)?);
    }
    fs::write(output.join("assets.rs"), generated)?;
    Ok(())
}

fn concatenate(files: &[PathBuf], separator: &str) -> io::Result<String> {
    let mut combined = String::new();
    for path in files {
        let source = fs::read_to_string(path).map_err(|error| {
            io::Error::new(error.kind(), format!("read {}: {error}", path.display()))
        })?;
        combined.push_str(&source);
        combined.push_str(separator);
    }
    Ok(combined)
}

fn minify_css(css: &str) -> Result<String, Box<dyn Error>> {
    let mut stylesheet = StyleSheet::parse(
        css,
        ParserOptions {
            filename: "src/templates (combined CSS)".into(),
            ..ParserOptions::default()
        },
    )
    .map_err(|error| io::Error::other(format!("parse CSS: {error}")))?;
    stylesheet
        .minify(MinifyOptions::default())
        .map_err(|error| io::Error::other(format!("minify CSS: {error}")))?;
    Ok(stylesheet
        .to_css(PrinterOptions {
            minify: true,
            ..PrinterOptions::default()
        })?
        .code)
}

/// Every oxc call is here, because oxc's 0.x API changes between releases.
/// Pages load one classic deferred script, so the source is parsed as a
/// script: top-level names stay global and are not renamed. A script that
/// does not parse fails the build.
fn minify_javascript(source: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let allocator = Allocator::default();
    let parsed = Parser::new(&allocator, source, SourceType::script()).parse();
    if let Some(error) = parsed.diagnostics.errors().next() {
        return Err(format!("parse JavaScript: {error}").into());
    }
    let mut program = parsed.program;
    let minified = Minifier::new(MinifierOptions::default()).minify(&allocator, &mut program);
    Ok(Codegen::new()
        .with_options(CodegenOptions::minify())
        .with_scoping(minified.scoping)
        .build(&program)
        .code
        .into_bytes())
}

/// Writes one asset to `OUT_DIR` and returns the constants that embed it.
fn asset(output: &Path, constant: &str, name: &str, bytes: &[u8]) -> io::Result<String> {
    fs::write(output.join(name), bytes)?;
    let digest = hex::encode(Sha256::digest(bytes));
    let (stem, extension) = name.rsplit_once('.').unwrap_or((name, ""));
    let url = format!("/assets/{stem}.{}.{extension}", &digest[..16]);
    Ok(format!(
        "pub const {constant}_URL: &str = {url:?};\n\
         pub const {constant}_BYTES: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{name}\"));\n"
    ))
}
